version: "3"
services:
  config-server:
    image: config-server:0.1
    environment:
      - TZ=Asia/Shanghai
      - spring.profiles.active=dev
    ports:
      - "18888:18888"
    extra_hosts:
      - "piggsoft.mapper:172.30.0.6"
    networks:
      - restful
networks:
  restful:
    driver: bridge